openapi: '3.0.2'
info:
  title: JongGeon Class API Interface Documents
  version: 0.1.0
  description: |
    JongGeon Class API Interface Documentation

servers:
- url: http://localhost:8806/
  description: local
  variables:
    basePath:
      default: /api
- url: https://jonggeon-class.kro.kr/
  description: Production
  variables:
    basePath:
      default: /api

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JGC_SESSION

security:
- cookieAuth: []

paths:
  /api/auth/login:
    $ref: paths/auth/login.yml#/login
  
  /api/auth/signup:
    $ref: paths/auth/signup.yml#/signup

  /api/auth/logout:
    $ref: paths/auth/logout.yml#/logout

  /api/product/product:
    $ref: paths/product/product.yml#/product

  /api/product/products:
    $ref: paths/product/products.yml#/products

  /api/product/carts:
    $ref: paths/product/carts.yml#/carts
  
  /api/product/add-to-cart:
    $ref: paths/product/add-to-cart.yml#/add-to-cart
  
  /api/product/update-cart-amount:
    $ref: paths/product/update-cart-amount.yml#/update-cart-amount
  
  /api/product/delete-cart-product:
    $ref: paths/product/delete-cart-product.yml#/delete-cart-product
  
  /api/product/add-review:
    $ref: paths/product/add-review.yml#/add-review
  
  /api/product/reviews:
    $ref: paths/product/reviews.yml#/reviews
  
  /api/product/categories:
    $ref: paths/product/categories.yml#/categories