products:
  get:
    summary: 상품 목록 조회
    description: >
      현재 존재하는 상품 목록을 조회합니다.
    parameters:
    - $ref: '../../components/page.yml#/page'
    - $ref: '../../components/page.yml#/pagesize'
    responses:
      200:
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: integer
                  enum: [8000]
                  description: >
                    dictionary:
                      * 8000 상품 조회 성공
                products:
                  $ref: '../../components/product.yml#/products'
                max_pagesize:
                  type: integer
                  description: 최대 페이지 수
                  default: 1
      500:
        description: Internal Server Error